<?php

/**
 * This is called from the "Article side blocks" block (bid = 42)
 */
function article_sideblock() {
  $url = $_REQUEST['q'];
  $output = "";

  //hebrew check
  $hebrew = substr($url, 0, 3);
  if ($hebrew == "en/") {
    $url = substr($url, 3);
  }

  //print "URL:   " . substr($url, 3);
  $query = "SELECT src FROM {url_alias} WHERE dst = '%s'";
  $res = db_query($query, $url);

  while ($record = db_fetch_array($res)) {
    $temp_url=$record[src];
  }

  $temp= explode('/', $temp_url);
  $nid = $temp[1];

  //print "system NID:   " . $nid;
  $node = node_load($nid);
  if ($node->field_b1_text[0]['value'] != '') {
    $output .= '<div class="article-block-1">';
    $output .= $node->field_b1_image[0]['view'];
    $output .= theme('imagecache', 'article_block', $node->field_b1_image[0]['filepath']);
    $output .= '<div class="block-text">' . $node->field_b1_text[0]['value'] . '</div>';
    $output .= '<a href="' . $node->field_b1_link[0]['value'] . '">' . t('For details') . '</a>';
    $output .= '</div>';
  }

  if ($node->field_b2_text[0]['value'] != '') {
    $output .= '<div class="article-block-2">';
    $output .= $node->field_b2_image[0]['view'];
    $output .= theme('imagecache', 'article_block',$node->field_b2_image[0]['filepath']);
    $output .= '<div class="block-text">' . $node->field_b2_text[0]['value'] . '</div>';
    $output .= '<a href="' . $node->field_b2_link[0]['value'] . '">' . t('For details') . '</a>';
    $output .= '</div>';
  }

  if ($node->field_b3_text[0]['value'] != '') {
    $output .= '<div class="article-block-3">';
    $output .= $node->field_b3_image[0]['view'];
    $output .= theme('imagecache', 'article_block', $node->field_b3_image[0]['filepath']);
    $output .= '<div class="block-text">' . $node->field_b3_text[0]['value'] . '</div>';
    $output .= '<a href="' . $node->field_b3_link[0]['value'] . '">' . t('For details') . '</a>';
    $output .= '</div>';
  }

  if ($node->field_b4_text[0]['value'] != '') {
    $output .= '<div class="article-block-4">';
    $output .= $node->field_b4_image[0]['view'];
    $output .= theme('imagecache', 'article_block', $node->field_b4_image[0]['filepath']);
    $output .= '<div class="block-text">' . $node->field_b4_text[0]['value'] . '</div>';
    $output .= '<a href="' . $node->field_b4_link[0]['value'] . '">' . t('For details') . '</a>';
    $output .= '</div>';
  }

  if ($node->field_b5_text[0]['value'] != '') {
    $output .= '<div class="article-block-5">';
    $output .= $node->field_b5_image[0]['view'];
    $output .= theme('imagecache', 'article_block', $node->field_b5_image[0]['filepath']);
    $output .= '<div class="block-text">' . $node->field_b5_text[0]['value'] . '</div>';
    $output .= '<a href="' . $node->field_b5_link[0]['value'] . '">' . t('For details') . '</a>';
    $output .= '</div>';
  }

  if ($node->field_b6_text[0]['value'] != '') {
    $output .= '<div class="article-block-6">';
    $output .= $node->field_b6_image[0]['view'];
    $output .= theme('imagecache', 'article_block', $node->field_b6_image[0]['filepath']);
    $output .= '<div class="block-text">' . $node->field_b6_text[0]['value'] . '</div>';
    $output .= '<a href="' . $node->field_b6_link[0]['value'] . '">' . t('For details') . '</a>';
    $output .= '</div>';
  }

  return $output;
}

function page_teacher_sideblock() {
  $url = $_REQUEST['q'];
  $output = "";

  //hebrew check
  $hebrew = substr($url, 0, 3);
  if ($hebrew == "en/") {
    $url = substr($url, 3);
  }

  $query = "SELECT src FROM {url_alias} WHERE dst = '%s'";
  $res = db_query($query, $url);
  while ($record = db_fetch_array($res)) {
    $temp_url = $record[src];
  }

  $temp = explode('/', $temp_url);
  $nid = $temp[1];

  //print "URL:   " . $url;
  if ($url == "") {
    $nid = 55;
  }

  if ($url == "en") {
    $nid = 10;
  }

  $node = node_load($nid);

  //$output .= "IT WORKS!";
  //$output .= $nid;

  if ($node->field_note1[0]['value'] != '') {
    $output .= '<div class="white-note">';
    // $output .= $node->field_b1_image[0]['view'];
    // $output .= theme('imagecache', 'article_block', $node->field_b1_image[0]['filepath']);
    $output .= '<div class="content">' . $node->field_note1[0]['value'] . '</div>';
    // $output .= '<a href="' . $node->field_b1_link[0]['value'] . '">' . t('For details') . '</a>';
    $output .= '</div>';
  }


  if ($node->field_videoblock[0]['value'] != '') {
    $output .= '<div class="video-sidbar">';
    // $output .= $node->field_b2_image[0]['view'];
    // $output .= theme('imagecache', 'article_block', $node->field_b2_image[0]['filepath']);
    $config = 'sidebar';
    $flashVars = array(
      'file' => $node->field_videoblock[0]['value'],
      'image' => $node->field_videopreview[0]['value']
    );

    $output .= '<div class="content">' . theme('jwplayermodule_render_player', $config, $flashVars) . '</div>';
    // $output .= '<a href="' . $node->field_b2_link[0]['value'] . '">' . t('For details') . '</a>';
    $output .= '</div>';
  }

  if ($node->field_note2[0]['value'] != '') {
    $output .= '<div class="yellow-note">';
    // $output .= $node->field_b3_image[0]['view'];
    // $output .= theme('imagecache', 'article_block', $node->field_b3_image[0]['filepath']);
    $output .= '<div class="content">' . $node->field_note2[0]['value'] . '</div>';
    // $output .= '<a href="' . $node->field_b3_link[0]['value'] . '">' . t('For details') . '</a>';
    $output .= '</div>';
  }

  //$output .=  "<pre>".print_r($node ,true)."</pre>";
  return $output;
}

function ca_interspire_sideblock_en() {
  $path = drupal_get_path('module', 'helper_functions');

  drupal_add_js($path . '/ca_interspire_sideblock.js');
  drupal_add_css($path . '/ca_interspire_sideblock.css');
  $is_course = helper_functions_is_course();
  if ($is_course) {
    drupal_add_css($path . '/ca_interspire_sideblock_hidedropdown.css');
    $request_uri = urldecode(drupal_substr(request_uri(), 1));
    drupal_add_js(array('ca_interspire_sideblock' => array('request_uri' => $request_uri)), 'setting');
  }
  drupal_add_js(array('ca_interspire_sideblock' => array('is_course' => $is_course)), 'setting');

  $content = <<<EOT
<div class="block block-webform" id="block-webform-client-block-interspire">
  <h2 class="block-title">Course signup</h2>
  <div class="content">
    <form class="webform-client-form compact-form" action="http://news.concept-academy.co.il/form.php?form=24" id="frmSS24" method="post" onsubmit="return CheckForm24(this);"><input name="format" type="hidden" value="h">
      <div>
        <div id="webform-component-name" class="webform-component webform-component-textfield">
          <div id="edit-submitted-name-wrapper" class="form-item compact-form-wrapper">
            <label class="compact-form-label" for="CustomFields_2_24">Name <span class="form-required" title="This field is required.">*</span></label> <input class="form-text required compact-form-field" id="CustomFields_2_24" name="CustomFields[2]" size="20" type="text" value="" onclick="setGFields(document.forms[0]);">
          </div>
        </div>
        <div id="webform-component-email" class="webform-component webform-component-email">
          <div id="edit-submitted-email-wrapper" class="form-item compact-form-wrapper">
            <label class="compact-form-label" for="email">Email <span class="form-required" title="This field is required.">*</span></label><input class="form-text required compact-form-field" name="email" id="email" type="text" value="">
          </div>
        </div>
        <div id="webform-component-phone" class="webform-component webform-component-textfield">
          <div id="edit-submitted-phone-wrapper" class="form-item compact-form-wrapper">
            <label class="compact-form-label" for="CustomFields_5_24">Phone <span class="form-required" title="This field is required.">*</span></label><input class="form-text required compact-form-field" id="CustomFields_5_24" name="CustomFields[5]" size="20" type="text" value="">
          </div>
        </div>
        <div id="webform-component-course" class="webform-component webform-component-select">
          <div id="edit-submitted-course-wrapper" class="form-item">
            <label for="CustomFields_13_24">Course: <span class="form-required" title="This field is required.">*</span></label>
            <select name="CustomFields[13]" class="form-select required" id="CustomFields_13_24">
              <option value="" selected="selected">select...</option>
              <option value="graphic_design">Graphic design</option>
              <option value="hair_dressing">Hair dressing</option>
              <option value="makeup">Makeup</option>
              <option value="photography">Photography</option>
              <option value="interior_design">Interior Design</option>
            </select>
          </div>
        </div>
        <div><!-- sourceURL:  -->
          <input id="CustomFields_26_24" name="CustomFields[26]" type="hidden" value="">
        </div>
        <div><!-- source: -->
          <input id="CustomFields_19_24" name="CustomFields[19]" type="hidden" value="">
        </div>
        <div><!-- term: -->
          <input id="CustomFields_21_24" name="CustomFields[21]" type="hidden" value="">
        </div>
        <div><!-- content: -->
          <input id="CustomFields_22_24" name="CustomFields[22]" type="hidden" value="">
        </div>
        <div><!-- campaign: -->
          <input id="CustomFields_23_24" name="CustomFields[23]" type="hidden" value="">
        </div>
        <div><!-- csegment: -->
          <input id="CustomFields_24_24" name="CustomFields[24]" type="hidden" value="">
        </div>
        <div><!-- nvisits: -->
          <input id="CustomFields_25_24" name="CustomFields[25]" type="hidden" value="">
        </div>
        <div class="form-item" id="edit-submitted-terms-1-wrapper">
          <label class="option" for="edit-submitted-terms-1"><input type="checkbox" name="submitted[terms][accept]" id="edit-submitted-terms-1" value="accept" checked="checked" class="form-checkbox"> I agree to the <a href="/terms-and-conditions">Terms and conditions</a></label>
        </div>
        <div id="edit-actions" class="form-actions form-wrapper">
          <input id="edit-submit" class="form-submit" type="submit" value="Send it"><br>
        </div>
      </div>
    </form>
  </div>
</div>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
EOT;

  return $content;
}

function ca_interspire_sideblock_he() {
  $path = drupal_get_path('module', 'helper_functions');

  drupal_add_js($path . '/ca_interspire_sideblock.js');
  drupal_add_css($path . '/ca_interspire_sideblock.css');
  $is_course = helper_functions_is_course();
  if ($is_course) {
    drupal_add_css($path . '/ca_interspire_sideblock_hidedropdown.css');
    $request_uri = urldecode(drupal_substr(request_uri(), 1));
    drupal_add_js(array('ca_interspire_sideblock' => array('request_uri' => $request_uri)), 'setting');
  }
  drupal_add_js(array('ca_interspire_sideblock' => array('is_course' => $is_course)), 'setting');

  $content = <<<EOT
<!--
Do not modify the NAME value of any of the INPUT fields
the FORM action, or any of the hidden fields (eg. input type=hidden).
These are all required for this form to function correctly.
-->
<div class="block block-webform" id="block-webform-client-block-interspire-heb">
  <h2 class="block-title">לפרטים נוספים</h2>
  <div class="content">
    <form class="webform-client-form compact-form" action="http://news.concept-academy.co.il/form.php?form=24" id="frmSS24" method="post" onsubmit="return CheckForm24(this);">
      <input name="format" type="hidden" value="h">
      <div>
        <div id="webform-component-name" class="webform-component webform-component-textfield">
          <div id="edit-submitted-name-wrapper" class="form-item compact-form-wrapper">
            <label class="compact-form-label" for="CustomFields_2_24">שם  <span class="form-required" title="This field is required.">*</span></label> <input class="form-text required compact-form-field" id="CustomFields_2_24" name="CustomFields[2]" size="25" type="text" value="" dir="rtl" onclick="setGFields(document.forms[0]);">
          </div>
        </div>
        <div id="webform-component-email" class="webform-component webform-component-email">
          <div id="edit-submitted-email-wrapper" class="form-item compact-form-wrapper">
            <label class="compact-form-label" for="email">דוא"ל  <span class="form-required" title="This field is required.">*</span></label><input class="form-text required compact-form-field" name="email" id="email" size="25" type="text" value="" dir="rtl">
          </div>
        </div>
        <div id="webform-component-phone" class="webform-component webform-component-textfield">
          <div id="edit-submitted-phone-wrapper" class="form-item compact-form-wrapper">
            <label class="compact-form-label" for="CustomFields_5_24">טלפון   <span class="form-required" title="This field is required.">*</span></label><input class="form-text required compact-form-field" id="CustomFields_5_24" name="CustomFields[5]" size="25" type="text" value="" dir="rtl">
          </div>
        </div>
        <div id="webform-component-course" class="webform-component webform-component-select">
          <div id="edit-submitted-course-wrapper" class="form-item">
            <label for="CustomFields_13_24">מעניין אותי ללמוד: <span class="form-required" title="This field is required.">*</span></label>
            <select name="CustomFields[13]" class="form-select required" id="CustomFields_13_24" style="width:150px" >
              <option value="" selected="selected">בחר...</option>
              <option value="מכינה">מכינה לעיצוב</option>
              <option value="עיצוב פנים">עיצוב פנים</option>
              <option value="הום סטיילינג">הום סטיילינג</option>
              <option value="הפקת אירועים">עיצוב והפקת אירועים</option>
              <option value="עיצוב אופנה">עיצוב אופנה</option>
              <option value="חלונות ראווה">עיצוב חלונות ראווה</option>
              <option value="עיצוב גרפי">עיצוב גרפי-תקשורת חזותית</option>
              <option value="עיצוב אתרי אינטרנט">עיצוב אתרי אינטרנט</option>
              <option value="סטיילינג">סטיילינג</option>
              <option value="קורס תפירה">קורס תפירה</option>
              <option value="עיצוב תעשייתי">עיצוב תעשייתי</option>
              <option value="שמלות כלה">עיצוב שמלות כלה וערב</option>
              <option value="שזירת פרחים">שזירת פרחים</option>
              <option value="דיווח על טעות בידיעה או כתבה">דיווח על טעות בידיעה או כתבה</option>
              <option value="הצעה לשיתוף פעולה - שיווק, פרסום או יח">הצעה לשיתוף פעולה - שיווק, פרסום או יח"צ</option>
              <option value="הנהח וכספים">הנה"ח וכספים</option>
              <option value="אני סטודנט המעוניין לפנות לדיקנית בנושא אישי">אני סטודנט המעוניין לפנות לדיקנית בנושא אישי</option>
              <option value="פניה למנהל אתר">פניה למנהל אתר</option>
              <option value="התעניינות במישרה פנויה">התעניינות במישרה פנויה</option>
            </select>
          </div>
        </div>
        <div><!-- sourceURL:  -->
          <input id="CustomFields_26_24" name="CustomFields[26]" type="hidden" value="">
        </div>
        <div><!-- source: -->
          <input id="CustomFields_19_24" name="CustomFields[19]" type="hidden" value="">
        </div>
        <div><!-- term: -->
          <input id="CustomFields_21_24" name="CustomFields[21]" type="hidden" value="">
        </div>
        <div><!-- content: -->
          <input id="CustomFields_22_24" name="CustomFields[22]" type="hidden" value="">
        </div>
        <div><!-- campaign: -->
          <input id="CustomFields_23_24" name="CustomFields[23]" type="hidden" value="">
        </div>
        <div><!-- csegment: -->
          <input id="CustomFields_24_24" name="CustomFields[24]" type="hidden" value="">
        </div>
        <div><!-- nvisits: -->
          <input id="CustomFields_25_24" name="CustomFields[25]" type="hidden" value="">
        </div>
        <div class="form-item" id="edit-submitted-terms-1-wrapper">
          <label class="option" for="edit-submitted-terms-1"><input type="checkbox" name="submitted[terms][accept]" id="edit-submitted-terms-1" value="accept" checked="checked" class="form-checkbox"> אישור לקבלת מידע</label>
        </div>
        <div id="edit-actions" class="form-actions form-wrapper">
          <input id="edit-submit" class="form-submit" type="submit" value="שלח"><br>
        </div>
      </div>
    </form>
  </div>
</div>
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
EOT;

  return $content;
}

/**
 * Detects whether the given page is a course node, or not.
 *
 * @return (boolean)
 *   TRUE is a page is a course node, FALSE otherwise
 */
function helper_functions_is_course() {
  $is_course = FALSE;

  if (arg(0) == 'node' && is_numeric(arg(1))) {
    $node = node_load(arg(1));
    if ($node->type == 'course') {
      $is_course = TRUE;
    }
  }

  return $is_course;
}
/**
 * Implementation of hook_preprocess_HOOK().
 *
 * It includes the contact_us_checkform.js to the /contact-us page
 *
 * @param array $vars
 *   The page variables
 */
function helper_functions_preprocess_page(&$vars) {
  if (request_uri() == '/contact-us') {
    drupal_add_js(drupal_get_path('module', 'helper_functions') . '/contact_us_checkform.js');
  }
}

/**
 * Implementation of hook_form_alter().
 */
/*
function mysite_form_alter(&$form, &$form_state, $form_id) {
  // print $form_id;
  switch ($form_id) {
    case 'blog_node_form':
      // remove some unwanted node editing fields
      $form['revision_information']['#access'] = 0;
      $form['menu']['#access'] = 0;
      $form['author']['#access'] = 0;
      // override node options permissions defined by 'administer nodes'
      $form['options']['#access'] = 1;
      $form['options']['status']['#access'] = 1;
      $form['options']['promote']['#access'] = 0;
      $form['options']['sticky']['#access'] = 0;
      break;

    case 'page_node_form':
      // don't ever allow page nodes to be promoted or sticky
      $form['options']['promote']['#access'] = 0;
      $form['options']['sticky']['#access'] = 0;
      break;
  }
}
*/
